
package controles;

import javax.swing.JOptionPane;

public class PagoMatriculaVisual extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public PagoMatriculaVisual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pago = new javax.swing.ButtonGroup();
        Turno = new javax.swing.ButtonGroup();
        Carrera = new javax.swing.ButtonGroup();
        lbCarrera = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        rbtnSoftware = new javax.swing.JRadioButton();
        rbtnElectronico = new javax.swing.JRadioButton();
        rbtnIndustrial = new javax.swing.JRadioButton();
        rbtnMecatronica = new javax.swing.JRadioButton();
        rbtnVespertino = new javax.swing.JRadioButton();
        rbtnMatutino = new javax.swing.JRadioButton();
        rbtnEfectivo = new javax.swing.JRadioButton();
        rbtnTarjeta = new javax.swing.JRadioButton();
        rbtnFinalizar = new javax.swing.JButton();
        txtfldPrecioFinal = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCarrera.setText("Elige tu carrera");

        lblPago.setText("Pago");

        lblTurno.setText("Turno");

        Carrera.add(rbtnSoftware);
        rbtnSoftware.setText("Desarrollo de Software");
        rbtnSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSoftwareActionPerformed(evt);
            }
        });

        Carrera.add(rbtnElectronico);
        rbtnElectronico.setText("Diseno Electronico");
        rbtnElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnElectronicoActionPerformed(evt);
            }
        });

        Carrera.add(rbtnIndustrial);
        rbtnIndustrial.setText("Industrial");
        rbtnIndustrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIndustrialActionPerformed(evt);
            }
        });

        Carrera.add(rbtnMecatronica);
        rbtnMecatronica.setText("Mecatronica");
        rbtnMecatronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMecatronicaActionPerformed(evt);
            }
        });

        Turno.add(rbtnVespertino);
        rbtnVespertino.setText("Vespertino");
        rbtnVespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVespertinoActionPerformed(evt);
            }
        });

        Turno.add(rbtnMatutino);
        rbtnMatutino.setText("Matutino");
        rbtnMatutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMatutinoActionPerformed(evt);
            }
        });

        Pago.add(rbtnEfectivo);
        rbtnEfectivo.setText("Efectivo");
        rbtnEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEfectivoActionPerformed(evt);
            }
        });

        Pago.add(rbtnTarjeta);
        rbtnTarjeta.setText("Tarjeta");
        rbtnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTarjetaActionPerformed(evt);
            }
        });

        rbtnFinalizar.setText("Finalizar");
        rbtnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFinalizarActionPerformed(evt);
            }
        });

        txtfldPrecioFinal.setEditable(false);
        txtfldPrecioFinal.setText("Precio Final $");
        txtfldPrecioFinal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPrecio.setText("El precio final es:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnElectronico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbtnSoftware)
                                .addGap(132, 132, 132)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbCarrera)
                            .addGap(204, 204, 204)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnMecatronica)
                            .addComponent(rbtnIndustrial))
                        .addGap(199, 199, 199)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnMatutino)
                    .addComponent(rbtnVespertino)
                    .addComponent(lblTurno)
                    .addComponent(rbtnFinalizar))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPago)
                            .addComponent(rbtnTarjeta)
                            .addComponent(rbtnEfectivo))
                        .addContainerGap(156, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfldPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCarrera)
                            .addComponent(lblPago)
                            .addComponent(lblTurno))
                        .addGap(28, 28, 28)
                        .addComponent(rbtnSoftware)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnElectronico)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnMecatronica)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnIndustrial)
                            .addComponent(rbtnFinalizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnMatutino)
                            .addComponent(rbtnEfectivo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnVespertino)
                            .addComponent(rbtnTarjeta))
                        .addGap(106, 106, 106)))
                .addComponent(lblPrecio)
                .addGap(26, 26, 26)
                .addComponent(txtfldPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnElectronicoActionPerformed

    private void rbtnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnEfectivoActionPerformed

    private void rbtnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFinalizarActionPerformed
        // TODO add your handling code here:
        
        String carrera = "";
    if (rbtnSoftware.isSelected()) {
        carrera = "Desarrollo de Software";
    } else if (rbtnElectronico.isSelected()) {
        carrera = "Diseño Electrónico";
    } else if (rbtnMecatronica.isSelected()) {
        carrera = "Mecatrónica";
    } else if (rbtnIndustrial.isSelected()) {
        carrera = "Industrial";
    }

    // Obtener selección de turno
    String turno = "";
    if (rbtnMatutino.isSelected()) {
        turno = "Matutino";
    } else if (rbtnVespertino.isSelected()) {
        turno = "Vespertino";
    }

    // Obtener selección de método de pago
    String metodoPago = "";
    if (rbtnEfectivo.isSelected()) {
        metodoPago = "Efectivo";
    } else if (rbtnTarjeta.isSelected()) {
        metodoPago = "Tarjeta";
    }

    // Validar que todas las opciones han sido seleccionadas
    if (carrera.isEmpty() || turno.isEmpty() || metodoPago.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona todas las opciones", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Crear instancia de PagoMatricula y calcular pago
    PagoMatricula pago = new PagoMatricula(carrera, turno, metodoPago);
    double total = pago.calcularPago();

    // Mostrar el total en el campo de texto
    txtfldPrecioFinal.setText("Precio Final: $" + total);
        
    }//GEN-LAST:event_rbtnFinalizarActionPerformed

    private void rbtnIndustrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIndustrialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnIndustrialActionPerformed

    private void rbtnSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSoftwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSoftwareActionPerformed

    private void rbtnMecatronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMecatronicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMecatronicaActionPerformed

    private void rbtnMatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMatutinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMatutinoActionPerformed

    private void rbtnVespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVespertinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnVespertinoActionPerformed

    private void rbtnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoMatriculaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoMatriculaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoMatriculaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoMatriculaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoMatriculaVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Carrera;
    private javax.swing.ButtonGroup Pago;
    private javax.swing.ButtonGroup Turno;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JRadioButton rbtnEfectivo;
    private javax.swing.JRadioButton rbtnElectronico;
    private javax.swing.JButton rbtnFinalizar;
    private javax.swing.JRadioButton rbtnIndustrial;
    private javax.swing.JRadioButton rbtnMatutino;
    private javax.swing.JRadioButton rbtnMecatronica;
    private javax.swing.JRadioButton rbtnSoftware;
    private javax.swing.JRadioButton rbtnTarjeta;
    private javax.swing.JRadioButton rbtnVespertino;
    private javax.swing.JTextField txtfldPrecioFinal;
    // End of variables declaration//GEN-END:variables
}
